-- Feel free to modify this file to match your development goal.
-- Here we only create 3 tables for demo purpose.

CREATE TABLE UserInfo (
    uid INT GENERATED BY DEFAULT AS IDENTITY, -- defaults to primary key?
    first_name VARCHAR(255) NOT NULL,
    mid_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    address VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE UserAcc (
    uid INT NOT NULL PRIMARY KEY,
    balance FLOAT NOT NULL,
    FOREIGN KEY (uid) REFERENCES UserInfo(uid)
);

-- go over in meeting
CREATE TABLE Seller (
    uid INT NOT NULL PRIMARY KEY,
    num_ratings INT NOT NULL,
    avg_rating INT NOT NULL,
    FOREIGN KEY (uid) REFERENCES UserAcc(uid)
);

CREATE TABLE Purchases (
    order_id INT GENERATED BY DEFAULT AS IDENTITY,
    product_id INT NOT NULL,
    date timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    uid INT NOT NULL,
    total_price FLOAT NOT NULL,
    num_items INT NOT NULL,
    fulfillment_status VARCHAR(255) NOT NULL,
    FOREIGN KEY (product_id) REFERENCES Products(product_id),
    FOREIGN KEY (uid) REFERENCES UserAcc(uid),
);

CREATE TABLE Products (
    product_id INT GENERATED BY DEFAULT AS IDENTITY,
    seller_id INT NOT NULL,
    category VARCHAR(255),
    name VARCHAR(255) UNIQUE NOT NULL,
    descrip TEXT NOT NULL, -- medium or long?
    img_link VARCHAR(255) UNIQUE NOT NULL,
    price FLOAT NOT NULL,
    available BOOLEAN DEFAULT TRUE, -- add availability to schema
    FOREIGN KEY (seller_id) REFERENCES Seller(uid)
);

-- bring up seller_id in meeting
CREATE TABLE UserCarts (
    uid INT NOT NULL PRIMARY KEY,
    product_id INT NOT NULL PRIMARY KEY,
    quantity INT NOT NULL,
    FOREIGN KEY (product_id) REFERENCES Products(product_id),
    FOREIGN KEY (uid) REFERENCES UserAcc(uid)
);

CREATE TABLE Feedback (
    buyer_id INT NOT NULL PRIMARY KEY,
    product_id INT NOT NULL PRIMARY KEY,
    seller_id INT NOT NULL PRIMARY KEY,
    rating INT NOT NULL,
    review TEXT NOT NULL,
    date timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    FOREIGN KEY (product_id) REFERENCES Products(product_id),
    FOREIGN KEY (seller_id) REFERENCES Seller(uid),
    FOREIGN KEY (buyer_id) REFERENCES UserAcc(uid)
);
CREATE TABLE SellerReviews (
    uid INT NOT NULL PRIMARY KEY,
    review_id INT GENERATED BY DEFAULT AS IDENTITY,
    review TEXT NOT NULL,
    FOREIGN KEY (uid) REFERENCES UserAcc(uid)
);